import { useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from '../lib/client'
import { useNav, useToasts } from '../state/stores'
import { Button, EmptyState, Panel, SectionTitle, SkeletonRows } from '../components/ui'
import { confirmDialog } from '../lib/dialogs'

export function EntryTemplatesScreen(): React.JSX.Element {
  const nav = useNav(); const toast = useToasts(); const queryClient = useQueryClient()
  const { data, isLoading } = useQuery({ queryKey: ['entry-templates'], queryFn: api.entryTemplates.list })
  const useTemplate = async (id: number): Promise<void> => { try { const draft = await api.entryTemplates.instantiate(id); await queryClient.invalidateQueries({ queryKey: ['voucher-drafts'] }); nav.go({ name: 'voucher-entry', workDraftId: draft.id }) } catch (error) { toast.push('error', (error as Error).message) } }
  const remove = async (id: number, name: string): Promise<void> => { if (!await confirmDialog({ title: 'Delete entry template', message: `Delete “${name}”? Existing vouchers and drafts are unaffected.`, confirmLabel: 'Delete template', danger: true })) return; try { await api.entryTemplates.remove(id); await queryClient.invalidateQueries({ queryKey: ['entry-templates'] }); toast.push('success', 'Template deleted') } catch (error) { toast.push('error', (error as Error).message) } }
  return <div className="mx-auto max-w-5xl"><SectionTitle right={<Button onClick={() => nav.go({ name: 'voucher-entry' })}>Record from voucher entry</Button>}>Entry templates & safe macros</SectionTitle><p className="mb-4 text-[12px] text-muted">Capture a safe entry sequence for rent, utilities, bank charges or standard journals. Every replay opens an editable draft and still passes normal validation, duplicate checks and approval—macros can never post automatically.</p><Panel className="overflow-hidden p-0">{isLoading ? <SkeletonRows rows={5} /> : !data?.length ? <EmptyState title="No safe macros" hint="Complete a voucher pattern, then choose Record safe macro" /> : <div data-testid="rows-entry-templates">{data.map((template) => <div key={template.id} className="grid grid-cols-[1fr_160px_auto] items-center gap-4 border-b border-line px-4 py-3 last:border-0"><div><p className="text-[13px] font-medium">{template.name}</p><p className="mt-0.5 text-[10.5px] text-muted">{template.voucherTypeName} · recorded by {template.createdBy}</p></div><span className="text-[11px] capitalize text-muted">{template.mode.replace('_', ' ')}</span><div className="flex gap-2"><Button onClick={() => void remove(template.id, template.name)}>Delete</Button><Button data-testid={`use-template-${template.id}`} variant="primary" onClick={() => void useTemplate(template.id)}>Replay safely</Button></div></div>)}</div>}</Panel></div>
}
