import { useMemo, useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { CheckCircle, ClipboardText, Package, Plus, SealCheck, ShoppingCart, Truck, WarningCircle } from '@phosphor-icons/react'
import type { GoodsReceipt, PurchaseOrder, PurchaseRequisition } from '@shared/procurement'
import type { VendorProfile } from '@shared/procurement'
import { todayISO, toDisplayDate } from '@shared/dates'
import { formatPaise } from '@shared/money'
import { api } from '../lib/client'
import { ItemPicker, LedgerPicker } from '../components/pickers'
import { MnemonicText } from '../components/MnemonicText'
import { AmountInput, Button, DateInput, EmptyState, Field, Modal, Panel, SectionTitle, Select, TextInput, ValidationSummary } from '../components/ui'
import { useNav, useSession, useToasts } from '../state/stores'

type Tab = 'requisitions' | 'orders' | 'receipts' | 'suppliers' | 'claims' | 'reorder' | 'vendors'
type ReqLineDraft = { key: number; stockItemId: number | null; qty: string; note: string }
type OrderLineDraft = { key: number; stockItemId: number | null; qty: string; ratePaise: number | null; gstRate: string }

const tabs: { id: Tab; label: string; key: string }[] = [
  { id: 'requisitions', label: 'Requisitions', key: 'R' },
  { id: 'orders', label: 'Purchase orders', key: 'O' },
  { id: 'receipts', label: 'Goods receipts', key: 'G' }
  ,{ id: 'suppliers', label: 'Supplier intelligence', key: 'S' }
  ,{ id: 'claims', label: 'Debit-note claims', key: 'D' }
  ,{ id: 'reorder', label: 'Reorder', key: 'E' }
  ,{ id: 'vendors', label: 'Vendors', key: 'V' }
]

function parseQty(text: string): number | null {
  if (!/^\d+(?:\.\d{1,3})?$/.test(text.trim())) return null
  const value = Number(text)
  return value > 0 ? Math.round(value * 1000) : null
}

function qty(value: number, symbol?: string): string {
  const text = (value / 1000).toLocaleString('en-IN', { maximumFractionDigits: 3 })
  return symbol ? `${text} ${symbol}` : text
}

function statusTone(status: string): string {
  if (['approved', 'issued', 'posted', 'received'].includes(status)) return 'border-dr/25 bg-dr/8 text-dr'
  if (['rejected', 'cancelled', 'closed'].includes(status)) return 'border-line bg-panel2 text-muted'
  if (['submitted', 'part_received'].includes(status)) return 'border-amber/30 bg-amber/10 text-amber'
  return 'border-line bg-panel2 text-ink'
}

function Status({ value }: { value: string }): React.JSX.Element {
  return <span className={`inline-flex rounded border px-1.5 py-0.5 text-[9.5px] font-semibold uppercase tracking-[0.06em] ${statusTone(value)}`}>{value.replace('_', ' ')}</span>
}

function Metric({ label, value, icon }: { label: string; value: React.ReactNode; icon: React.ReactNode }): React.JSX.Element {
  return <Panel className="px-3 py-2.5"><div className="flex items-center gap-1.5 text-muted">{icon}<span className="text-[9.5px] font-semibold uppercase tracking-[0.08em]">{label}</span></div><div className="mt-1 text-[17px] font-semibold tracking-[-0.02em]">{value}</div></Panel>
}

export function ProcurementScreen({ initialTab = 'requisitions' }: { initialTab?: Tab }): React.JSX.Element {
  const nav = useNav()
  const queryClient = useQueryClient()
  const toast = useToasts()
  const [reqModal, setReqModal] = useState(false)
  const [orderSource, setOrderSource] = useState<PurchaseRequisition | null | undefined>(undefined)
  const [receiptOrder, setReceiptOrder] = useState<PurchaseOrder | null>(null)
  const [busyKey, setBusyKey] = useState('')
  const requisitions = useQuery({ queryKey: ['procurement-requisitions'], queryFn: api.procurement.requisitions })
  const orders = useQuery({ queryKey: ['procurement-orders'], queryFn: api.procurement.orders })
  const receipts = useQuery({ queryKey: ['procurement-receipts'], queryFn: api.procurement.receipts })

  const refresh = async (): Promise<void> => {
    await Promise.all([
      queryClient.invalidateQueries({ queryKey: ['procurement-requisitions'] }),
      queryClient.invalidateQueries({ queryKey: ['procurement-orders'] }),
      queryClient.invalidateQueries({ queryKey: ['procurement-receipts'] }),
      queryClient.invalidateQueries({ queryKey: ['stockSummary'] })
    ])
  }
  const act = async (key: string, work: () => Promise<unknown>, message: string): Promise<void> => {
    setBusyKey(key)
    try { await work(); await refresh(); toast.push('success', message) }
    catch (error) { toast.push('error', error instanceof Error ? error.message : String(error)) }
    finally { setBusyKey('') }
  }
  const openReqCount = requisitions.data?.filter((row) => ['draft', 'submitted', 'approved'].includes(row.status)).length ?? 0
  const openOrders = orders.data?.filter((row) => ['draft', 'issued', 'part_received'].includes(row.status)) ?? []
  const outstandingUnits = openOrders.reduce((sum, row) => sum + row.lines.reduce((lineSum, line) => lineSum + line.outstandingQtyMilli, 0), 0)

  return <div className="mx-auto max-w-[1280px] p-5" data-testid="procurement-screen">
    <SectionTitle right={<div className="flex gap-2"><Button onClick={() => setReqModal(true)}><Plus size={14} /> New requisition</Button><Button variant="primary" onClick={() => setOrderSource(null)}><ShoppingCart size={14} /> New order</Button></div>}>Procurement</SectionTitle>
    <p className="-mt-2 mb-4 max-w-3xl text-[11.5px] text-muted">A controlled trail from internal demand to supplier order and inspected stock receipt. Requisitions and orders never touch the books; accepted goods post inventory at GRN.</p>
    <div className="mb-4 grid grid-cols-4 gap-2">
      <Metric label="Open requests" value={openReqCount} icon={<ClipboardText size={15} />} />
      <Metric label="Open orders" value={openOrders.length} icon={<ShoppingCart size={15} />} />
      <Metric label="Outstanding quantity" value={qty(outstandingUnits)} icon={<Package size={15} />} />
      <Metric label="Receipts posted" value={receipts.data?.filter((row) => row.status === 'posted').length ?? 0} icon={<SealCheck size={15} />} />
    </div>
    <div className="mb-3 flex gap-1 border-b border-line" role="tablist">
      {tabs.map((tab) => <button key={tab.id} role="tab" aria-label={tab.label} aria-selected={initialTab === tab.id} className={`relative px-3 py-2 text-[11.5px] font-medium ${initialTab === tab.id ? 'text-ink after:absolute after:inset-x-2 after:bottom-0 after:h-0.5 after:bg-amberbar' : 'text-muted hover:text-ink'}`} onClick={() => nav.replace({ name: 'procurement', tab: tab.id })}><MnemonicText label={tab.label} mnemonic={tab.key.toLowerCase()} /></button>)}
    </div>
    {initialTab === 'requisitions' && <RequisitionList rows={requisitions.data ?? []} loading={requisitions.isLoading} busyKey={busyKey} onStatus={(row, status, note) => void act(`req-${row.id}`, () => api.procurement.setRequisitionStatus(row.id, status, note), `${row.number} marked ${status}`)} onConvert={setOrderSource} />}
    {initialTab === 'orders' && <OrderList rows={orders.data ?? []} loading={orders.isLoading} busyKey={busyKey} onStatus={(row, status) => void act(`po-${row.id}`, () => api.procurement.setOrderStatus(row.id, status), `${row.number} marked ${status}`)} onReceive={setReceiptOrder} />}
    {initialTab === 'receipts' && <ReceiptList rows={receipts.data ?? []} loading={receipts.isLoading} onVoucher={(id) => nav.go({ name: 'voucher-entry', voucherId: id })} />}
    {initialTab === 'suppliers' && <SupplierIntelligence />}
    {initialTab === 'claims' && <DebitNoteClaims />}
    {initialTab === 'reorder' && <ReorderWorkspace />}
    {initialTab === 'vendors' && <VendorWorkspace />}
    {reqModal && <RequisitionModal onClose={() => setReqModal(false)} onSaved={async (row) => { setReqModal(false); await refresh(); toast.push('success', `${row.number} saved as draft`) }} />}
    {orderSource !== undefined && <OrderModal source={orderSource} onClose={() => setOrderSource(undefined)} onSaved={async (row) => { setOrderSource(undefined); await refresh(); nav.replace({ name: 'procurement', tab: 'orders' }); toast.push('success', `${row.number} saved as draft`) }} />}
    {receiptOrder && <ReceiptModal order={receiptOrder} onClose={() => setReceiptOrder(null)} onSaved={async (row) => { setReceiptOrder(null); await refresh(); nav.replace({ name: 'procurement', tab: 'receipts' }); toast.push('success', `${row.number} posted; accepted stock is now on hand`) }} />}
  </div>
}

function VendorWorkspace():React.JSX.Element{
  const queryClient=useQueryClient();const toast=useToasts();const role=useSession((state)=>state.user?.role??'owner');const [editing,setEditing]=useState<VendorProfile|null|undefined>(undefined);const [busy,setBusy]=useState<number|null>(null);const vendors=useQuery({queryKey:['procurement-vendors'],queryFn:api.procurement.vendors});const refresh=async()=>queryClient.invalidateQueries({queryKey:['procurement-vendors']});const status=async(row:VendorProfile,next:'verified'|'blocked')=>{let note:string|null=null;if(next==='blocked'){note=window.prompt('Reason for blocking this vendor');if(!note)return}setBusy(row.ledgerId);try{await api.procurement.setVendorStatus(row.ledgerId,next,note);await refresh();toast.push('success',`${row.supplierName} marked ${next}`)}catch(error){toast.push('error',error instanceof Error?error.message:String(error))}finally{setBusy(null)}}
  return <div className="grid gap-3"><Panel className="flex items-center justify-between px-4 py-3"><div><p className="text-[11.5px] font-semibold">Vendor onboarding & compliance</p><p className="mt-0.5 text-[10.5px] text-muted">Confirm contact, banking and MSME identity; duplicate tax IDs and bank accounts block verification.</p></div><Button data-testid="onboard-vendor" variant="primary" onClick={()=>setEditing(null)}><Plus size={13}/> Onboard vendor</Button></Panel>{!vendors.isLoading&&!vendors.data?.length?<EmptyState title="No vendor profiles" hint="Supplier ledgers remain usable, but onboarding adds verified contact, bank and MSME evidence before payment."/>:<Panel><div className="grid grid-cols-[1fr_180px_180px_130px_250px] border-b border-line bg-panel2 px-3 py-2 text-[9px] font-semibold uppercase tracking-[0.07em] text-muted"><span>Supplier</span><span>Contact</span><span>Bank</span><span>Status</span><span className="text-right">Review</span></div>{vendors.data?.map((row)=><div key={row.id} data-testid={`vendor-${row.ledgerId}`} className="grid grid-cols-[1fr_180px_180px_130px_250px] items-center border-b border-line px-3 py-2.5 last:border-0"><div><b className="text-[11.5px]">{row.supplierName}</b><p className="text-[9.5px] text-muted">{row.gstin?`GSTIN ${row.gstin}`:row.pan?`PAN ${row.pan}`:'Unregistered / tax ID pending'}</p></div><div className="text-[10.5px]"><p>{row.contactName??'—'}</p><p className="truncate text-muted">{row.email??row.phone??'No contact channel'}</p></div><div className="text-[10.5px]"><p>{row.bankName??'—'}</p><p className="num text-muted">{row.bankAccount??'Bank pending'}{row.ifsc?` · ${row.ifsc}`:''}</p></div><div><Status value={row.status}/>{row.issues.length>0&&<p className={`mt-1 text-[9px] ${row.issues.some((issue)=>issue.severity==='block')?'text-cr':'text-amber'}`}>{row.issues.length} duplicate signal{row.issues.length===1?'':'s'}</p>}</div><div className="flex justify-end gap-1"><Button variant="ghost" onClick={()=>setEditing(row)}>Edit</Button>{role==='owner'&&row.status!=='blocked'&&<Button variant="ghost" disabled={busy===row.ledgerId} onClick={()=>void status(row,'blocked')}>Block</Button>}{role==='owner'&&row.status!=='verified'&&<Button variant="primary" data-testid={`verify-vendor-${row.ledgerId}`} disabled={busy===row.ledgerId} onClick={()=>void status(row,'verified')}>Verify</Button>}</div></div>)}</Panel>}{editing!==undefined&&<VendorProfileModal profile={editing} onClose={()=>setEditing(undefined)} onSaved={async(row)=>{setEditing(undefined);await refresh();toast.push('success',`${row.supplierName} profile saved for review`)}}/>}</div>
}

function VendorProfileModal({profile,onClose,onSaved}:{profile:VendorProfile|null;onClose:()=>void;onSaved:(row:VendorProfile)=>Promise<void>}):React.JSX.Element{
  const toast=useToasts();const [ledgerId,setLedgerId]=useState<number|null>(profile?.ledgerId??null);const [contactName,setContactName]=useState(profile?.contactName??'');const [email,setEmail]=useState(profile?.email??'');const [phone,setPhone]=useState(profile?.phone??'');const [bankName,setBankName]=useState(profile?.bankName??'');const [bankAccount,setBankAccount]=useState(profile?.bankAccount?.startsWith('••••')?'':profile?.bankAccount??'');const [ifsc,setIfsc]=useState(profile?.ifsc??'');const [udyam,setUdyam]=useState(profile?.udyamNumber??'');const [saving,setSaving]=useState(false);const issues=[...(ledgerId?[]:['Choose a supplier ledger']),...(!contactName.trim()?['Enter the primary contact name']:[]),...(!email.trim()&&!phone.trim()?['Enter an email or phone number']:[]),...((bankAccount.trim()&&!ifsc.trim())||(!bankAccount.trim()&&ifsc.trim())?['Bank account and IFSC must be entered together']:[])];const save=async()=>{if(issues.length||saving||!ledgerId)return;setSaving(true);try{await onSaved(await api.procurement.saveVendor({ledgerId,contactName:contactName.trim()||null,email:email.trim()||null,phone:phone.trim()||null,bankName:bankName.trim()||null,bankAccount:bankAccount.trim()||null,ifsc:ifsc.trim()||null,udyamNumber:udyam.trim()||null}))}catch(error){toast.push('error',error instanceof Error?error.message:String(error));setSaving(false)}}
  return <Modal title={profile?`Edit ${profile.supplierName}`:'Onboard supplier'} onClose={onClose} dirty wide><div className="grid gap-4"><Field label="Supplier ledger"><LedgerPicker value={ledgerId} onPick={setLedgerId} autoFocus={!profile} testId="picker-vendor-ledger" placeholder="Sundry creditor" filter={(ledger,groups)=>{let group=groups.get(ledger.groupId);while(group){if(group.name==='Sundry Creditors')return true;group=group.parentId?groups.get(group.parentId):undefined}return false}}/></Field><div className="grid grid-cols-3 gap-3"><Field label="Primary contact"><TextInput data-testid="input-vendor-contact" value={contactName} maxLength={120} onChange={(event)=>setContactName(event.target.value)}/></Field><Field label="Email"><TextInput data-testid="input-vendor-email" value={email} type="email" maxLength={160} onChange={(event)=>setEmail(event.target.value)}/></Field><Field label="Phone"><TextInput value={phone} maxLength={30} onChange={(event)=>setPhone(event.target.value)}/></Field></div><div className="grid grid-cols-3 gap-3"><Field label="Bank name"><TextInput value={bankName} maxLength={120} onChange={(event)=>setBankName(event.target.value)}/></Field><Field label="Account number" hint={profile?.bankAccount?.startsWith('••••')?'Viewer masking is active; leave blank to clear only with edit rights.':undefined}><TextInput data-testid="input-vendor-account" value={bankAccount} maxLength={40} className="num" onChange={(event)=>setBankAccount(event.target.value)}/></Field><Field label="IFSC"><TextInput data-testid="input-vendor-ifsc" value={ifsc} maxLength={11} className="uppercase num" onChange={(event)=>setIfsc(event.target.value)}/></Field></div><Field label="Udyam / MSME number" hint="Optional · UDYAM-XX-00-0000000"><TextInput value={udyam} maxLength={24} className="uppercase num" onChange={(event)=>setUdyam(event.target.value)}/></Field><ValidationSummary issues={issues}/><div className="flex items-center justify-between"><p className="max-w-xl text-[10.5px] text-muted">Saving resets verification to draft. An owner verifies only after duplicate and compliance signals are clear.</p><div className="flex gap-2"><Button onClick={onClose}>Cancel</Button><Button data-testid="save-vendor-profile" variant="primary" disabled={saving||issues.length>0} onClick={()=>void save()}>{saving?'Saving…':'Save for review'}</Button></div></div></div></Modal>
}

function ReorderWorkspace():React.JSX.Element{
  const asOn=todayISO();const nav=useNav();const toast=useToasts();const queryClient=useQueryClient();const [selected,setSelected]=useState<Set<number>>(new Set());const [busy,setBusy]=useState(false);const suggestions=useQuery({queryKey:['procurement-reorder',asOn],queryFn:()=>api.procurement.reorderSuggestions(asOn)})
  const eligible=(suggestions.data??[]).filter((row)=>row.supplierLedgerId&&row.lastRatePaise!=null);const create=async():Promise<void>=>{if(!selected.size)return;setBusy(true);try{const orders=await api.procurement.createReorderOrders(asOn,[...selected]);toast.push('success',`${orders.length} grouped purchase-order draft${orders.length===1?'':'s'} created`);await Promise.all([queryClient.invalidateQueries({queryKey:['procurement-orders']}),queryClient.invalidateQueries({queryKey:['procurement-reorder']} )]);nav.replace({name:'procurement',tab:'orders'})}catch(error){toast.push('error',error instanceof Error?error.message:String(error));setBusy(false)}}
  if(!suggestions.isLoading&&!suggestions.data?.length)return <EmptyState title="Stock is above every reorder level" hint="Suggestions appear when on-hand quantity falls below an item’s configured reorder level."/>
  return <div className="grid gap-3">
    <Panel className="flex items-center justify-between px-4 py-3"><div><p className="text-[11.5px] font-semibold">Owner-reviewed reorder suggestions</p><p className="mt-0.5 text-[10.5px] text-muted">Total uses the latest non-cancelled supplier and rate, then groups selected items into one editable draft PO per supplier. No order is issued automatically.</p></div><Button data-testid="create-reorder-orders" variant="primary" disabled={!selected.size||busy} onClick={()=>void create()}>{busy?'Creating…':`Create ${new Set(eligible.filter((row)=>selected.has(row.stockItemId)).map((row)=>row.supplierLedgerId)).size||''} grouped PO draft${selected.size===1?'':'s'}`}</Button></Panel>
    <Panel>
      <div className="grid grid-cols-[38px_1fr_120px_120px_220px_130px] gap-3 border-b border-line bg-panel2 px-3 py-2 text-[9px] font-semibold uppercase tracking-[0.07em] text-muted"><span/><span>Item</span><span className="text-right">On hand</span><span className="text-right">Reorder at</span><span>Preferred supplier</span><span className="text-right">Suggested</span></div>
      {suggestions.data?.map((row)=><div key={row.stockItemId} className="grid grid-cols-[38px_1fr_120px_120px_220px_130px] items-center gap-3 border-b border-line px-3 py-2.5 text-[11px] last:border-0"><input type="checkbox" data-testid={`select-reorder-${row.stockItemId}`} checked={selected.has(row.stockItemId)} disabled={!row.supplierLedgerId||row.lastRatePaise==null} onChange={()=>setSelected((current)=>{const next=new Set(current);next.has(row.stockItemId)?next.delete(row.stockItemId):next.add(row.stockItemId);return next})}/><div><b>{row.itemName}</b>{!row.supplierLedgerId&&<p className="text-[9.5px] text-cr">No supplier history — create a PO manually first</p>}</div><span className={`num text-right ${row.closingQtyMilli<0?'text-cr':'text-amber'}`}>{qty(row.closingQtyMilli,row.unitSymbol)}</span><span className="num text-right text-muted">{qty(row.reorderLevelMilli,row.unitSymbol)}</span><span className="truncate">{row.supplierName??'—'}{row.lastRatePaise!=null&&<small className="ml-1 text-muted">· ₹{formatPaise(row.lastRatePaise)}</small>}</span><span className="num text-right font-medium">{qty(row.suggestedQtyMilli,row.unitSymbol)}</span></div>)}
    </Panel>
  </div>
}

function DebitNoteClaims(): React.JSX.Element {
  const nav = useNav(); const toast = useToasts(); const [busy, setBusy] = useState('')
  const claims = useQuery({ queryKey: ['procurement-debit-note-claims'], queryFn: api.procurement.debitNoteClaims })
  const prepare = async (sourceKey: string): Promise<void> => { setBusy(sourceKey); try { const draft=await api.procurement.createDebitNoteDraft(sourceKey); nav.go({name:'voucher-entry',workDraftId:draft.id}) } catch(error){toast.push('error',error instanceof Error?error.message:String(error));setBusy('')} }
  if(!claims.isLoading&&!claims.data?.length)return <EmptyState title="No open debit-note claims" hint="Recorded rejected goods, closed-order shortages and invoice rates above the PO become reviewable claims here." />
  return <Panel><div className="grid grid-cols-[135px_190px_1fr_140px_180px] border-b border-line bg-panel2 px-3 py-2 text-[9px] font-semibold uppercase tracking-[0.07em] text-muted"><span>Reason</span><span>Supplier</span><span>Evidence</span><span className="text-right">Taxable claim</span><span className="text-right">Action</span></div>{(claims.data??[]).map((claim)=><div key={claim.sourceKey} data-testid={`debit-note-claim-${claim.sourceKey}`} className="grid grid-cols-[135px_190px_1fr_140px_180px] items-center border-b border-line px-3 py-2.5 last:border-0"><Status value={claim.reason}/><div><b className="text-[11.5px]">{claim.supplierName}</b><p className="text-[9.5px] text-muted">{claim.purchaseOrderNumber}</p></div><div><p className="text-[11px]">{claim.detail}</p><p className="mt-0.5 truncate text-[9.5px] text-muted">{claim.lines.map((line)=>`${line.itemName} · ${qty(line.qtyMilli)}`).join(', ')}</p></div><span className="num text-right text-[11.5px]">₹{formatPaise(claim.amount)}</span><div className="text-right"><Button data-testid={`prepare-debit-note-${claim.sourceKey}`} variant="primary" disabled={busy===claim.sourceKey} onClick={()=>void prepare(claim.sourceKey)}>{busy===claim.sourceKey?'Preparing…':'Prepare debit note'}</Button></div></div>)}</Panel>
}

function SupplierIntelligence(): React.JSX.Element {
  const [stockItemId, setStockItemId] = useState<number | null>(null)
  const {from,to}=useSession()
  const comparison = useQuery({ queryKey: ['procurement-supplier-comparison', stockItemId], queryFn: () => api.procurement.supplierComparison(stockItemId!), enabled: stockItemId != null })
  const concentration=useQuery({queryKey:['procurement-supplier-concentration',from,to],queryFn:()=>api.procurement.supplierConcentration(from,to)})
  return <div className="grid gap-3">
    {(concentration.data?.rows.length??0)>0&&<Panel><div className="flex items-center justify-between border-b border-line bg-panel2 px-4 py-2"><div><p className="text-[11.5px] font-semibold">Supplier concentration · current period</p><p className="text-[10px] text-muted">Purchase share plus sole-source exposure from purchase-order history.</p></div><span className="text-[11px]"><b>₹{formatPaise(concentration.data?.totalPurchases??0)}</b> purchases</span></div><div className="grid grid-cols-[1fr_140px_120px_120px_1fr] px-4 py-1.5 text-[9px] font-semibold uppercase tracking-[0.07em] text-muted"><span>Supplier</span><span className="text-right">Spend</span><span className="text-right">Share</span><span className="text-right">Sole-source</span><span className="pl-5">Categories</span></div>{concentration.data?.rows.slice(0,8).map((row)=><div key={row.supplierLedgerId} className="grid grid-cols-[1fr_140px_120px_120px_1fr] items-center border-t border-line px-4 py-2 text-[10.5px]"><span className="flex items-center gap-2"><b>{row.supplierName}</b><span className={`rounded border px-1 py-0.5 text-[8px] font-semibold uppercase ${row.risk==='high'?'border-cr/25 bg-cr/5 text-cr':row.risk==='watch'?'border-amber/25 bg-amber/5 text-amber':'border-dr/20 bg-dr/5 text-dr'}`}>{row.risk}</span></span><span className="num text-right">₹{formatPaise(row.purchaseAmount)}</span><span className="num text-right">{row.sharePercent.toFixed(1)}%</span><span className="num text-right">{row.soleSourcedItemCount} item{row.soleSourcedItemCount===1?'':'s'}</span><span className="truncate pl-5 text-muted">{row.categories.join(', ')||'—'}</span></div>)}</Panel>}
    <Panel className="grid grid-cols-[340px_1fr] items-center gap-5 px-4 py-3"><Field label="Compare suppliers for"><ItemPicker testId="picker-supplier-comparison-item" value={stockItemId} onPick={setStockItemId} /></Field><p className="text-[10.5px] leading-4 text-muted">Rates include an indicative tax-inclusive view; delivery and rejection scores come only from posted GRNs. No opaque score hides the underlying evidence.</p></Panel>
    {!stockItemId ? <EmptyState title="Choose an item to compare suppliers" hint="Total will rank suppliers by effective latest price, then show terms, lead time, on-time delivery and rejection history side by side." /> : !comparison.isLoading && !comparison.data?.length ? <EmptyState title="No supplier evidence yet" hint="Issue a purchase order for this item to begin building a comparable history." /> : <Panel>
      <div className="grid grid-cols-[1fr_130px_130px_100px_100px_110px_120px_100px] border-b border-line bg-panel2 px-3 py-2 text-[9px] font-semibold uppercase tracking-[0.07em] text-muted"><span>Supplier</span><span className="text-right">Latest / unit</span><span className="text-right">Incl. GST</span><span className="text-right">Terms</span><span className="text-right">Orders</span><span className="text-right">Lead time</span><span className="text-right">On time</span><span className="text-right">Rejected</span></div>
      {(comparison.data ?? []).map((row, index) => <div key={row.supplierLedgerId} data-testid={`supplier-comparison-${row.supplierLedgerId}`} className="grid grid-cols-[1fr_130px_130px_100px_100px_110px_120px_100px] items-center border-b border-line px-3 py-2.5 text-[11px] last:border-0"><div><div className="flex items-center gap-2"><b>{row.supplierName}</b>{index === 0 && <span className="rounded border border-dr/25 bg-dr/5 px-1 py-0.5 text-[8.5px] font-semibold uppercase text-dr">price lead</span>}</div><p className="mt-0.5 text-[9.5px] text-muted">Avg ₹{formatPaise(row.weightedAverageRatePaise)} · {qty(row.acceptedQtyMilli)} accepted</p></div><span className="num text-right">₹{formatPaise(row.lastRatePaise)}</span><span className="num text-right font-medium">₹{formatPaise(row.effectiveRateIncTaxPaise)}</span><span className="text-right text-muted">{row.creditDays != null ? `${row.creditDays} days` : '—'}</span><span className="num text-right">{row.orderCount}</span><span className="num text-right">{row.averageLeadDays != null ? `${row.averageLeadDays.toFixed(1)} days` : '—'}</span><span className={`num text-right ${row.onTimeDeliveryRate != null && row.onTimeDeliveryRate >= 90 ? 'text-dr' : row.onTimeDeliveryRate != null && row.onTimeDeliveryRate < 70 ? 'text-cr' : ''}`}>{row.onTimeDeliveryRate != null ? `${row.onTimeDeliveryRate.toFixed(0)}%` : '—'}</span><span className={`num text-right ${row.rejectionRate > 5 ? 'text-cr' : row.rejectionRate > 0 ? 'text-amber' : 'text-dr'}`}>{row.rejectionRate.toFixed(1)}%</span></div>)}
    </Panel>}
  </div>
}

function RequisitionList({ rows, loading, busyKey, onStatus, onConvert }: { rows: PurchaseRequisition[]; loading: boolean; busyKey: string; onStatus: (row: PurchaseRequisition, status: 'submitted' | 'approved' | 'rejected' | 'cancelled', note?: string) => void; onConvert: (row: PurchaseRequisition) => void }): React.JSX.Element {
  if (!loading && !rows.length) return <EmptyState title="No purchase requisitions" hint="Capture demand before speaking to a supplier. Approval creates an audit-ready handoff to purchasing." />
  return <Panel><div className="grid grid-cols-[120px_90px_1fr_150px_140px_270px] border-b border-line bg-panel2 px-3 py-2 text-[9.5px] font-semibold uppercase tracking-[0.08em] text-muted"><span>Request</span><span>Date</span><span>Need</span><span>Department</span><span>Status</span><span className="text-right">Next action</span></div>
    {rows.map((row) => <div key={row.id} data-testid={`requisition-${row.id}`} className="grid grid-cols-[120px_90px_1fr_150px_140px_270px] items-center border-b border-line px-3 py-2.5 last:border-0">
      <div><b className="text-[12px]">{row.number}</b><p className="text-[9.5px] text-muted">{row.requestedBy}</p></div><span className="num text-[11px] text-muted">{toDisplayDate(row.date)}</span>
      <div className="min-w-0"><p className="truncate text-[11.5px]">{row.lines.map((line) => `${line.itemName} · ${qty(line.qtyMilli, line.unitSymbol)}`).join('  /  ')}</p><p className="truncate text-[9.5px] text-muted">{row.note || (row.neededBy ? `Needed ${toDisplayDate(row.neededBy)}` : 'No delivery deadline')}</p></div>
      <span className="truncate text-[11px] text-muted">{row.department || '—'}</span><Status value={row.status} />
      <div className="flex justify-end gap-1">{row.status === 'draft' && <><Button disabled={busyKey === `req-${row.id}`} variant="ghost" onClick={() => onStatus(row, 'cancelled')}>Cancel</Button><Button data-testid={`submit-requisition-${row.id}`} onClick={() => onStatus(row, 'submitted')}>Submit</Button></>}{row.status === 'submitted' && <><Button variant="ghost" onClick={() => { const note = window.prompt('Reason for rejection'); if (note) onStatus(row, 'rejected', note) }}>Reject</Button><Button data-testid={`approve-requisition-${row.id}`} variant="primary" onClick={() => onStatus(row, 'approved')}>Approve</Button></>}{row.status === 'approved' && <Button data-testid={`convert-requisition-${row.id}`} variant="primary" onClick={() => onConvert(row)}>Create PO</Button>}</div>
    </div>)}
  </Panel>
}

function OrderList({ rows, loading, busyKey, onStatus, onReceive }: { rows: PurchaseOrder[]; loading: boolean; busyKey: string; onStatus: (row: PurchaseOrder, status: 'issued' | 'closed' | 'cancelled') => void; onReceive: (row: PurchaseOrder) => void }): React.JSX.Element {
  if (!loading && !rows.length) return <EmptyState title="No purchase orders" hint="Convert an approved requisition, or create a direct order for an authorised purchase." />
  return <Panel><div className="grid grid-cols-[115px_180px_1fr_150px_145px_250px] border-b border-line bg-panel2 px-3 py-2 text-[9.5px] font-semibold uppercase tracking-[0.08em] text-muted"><span>Order</span><span>Supplier</span><span>Fulfilment</span><span>Value before tax</span><span>Status</span><span className="text-right">Action</span></div>
    {rows.map((row) => { const value = row.lines.reduce((sum, line) => sum + Math.round(line.qtyOrderedMilli * line.ratePaise / 1000), 0); const ordered = row.lines.reduce((sum, line) => sum + line.qtyOrderedMilli, 0); const accepted = row.lines.reduce((sum, line) => sum + line.qtyAcceptedMilli, 0); return <div key={row.id} data-testid={`purchase-order-${row.id}`} className="grid grid-cols-[115px_180px_1fr_150px_145px_250px] items-center border-b border-line px-3 py-2.5 last:border-0">
      <div><b className="text-[12px]">{row.number}</b><p className="num text-[9.5px] text-muted">{toDisplayDate(row.date)}</p></div><div className="min-w-0"><p className="truncate text-[11.5px] font-medium">{row.supplierName}</p><p className="text-[9.5px] text-muted">{row.expectedDate ? `Expected ${toDisplayDate(row.expectedDate)}` : 'No delivery date'}</p></div>
      <div className="pr-5"><div className="mb-1 flex justify-between text-[9.5px] text-muted"><span>{qty(accepted)} accepted · {qty(row.lines.reduce((sum, line) => sum + line.qtyBilledMilli, 0))} billed</span><span>{qty(ordered)} ordered</span></div><div className="h-1.5 overflow-hidden rounded bg-panel2"><div className="h-full bg-dr" style={{ width: `${ordered ? Math.min(100, accepted / ordered * 100) : 0}%` }} /></div><p className="mt-1 truncate text-[9.5px] text-muted">{row.lines.map((line) => line.itemName).join(', ')}</p></div>
      <span className="num text-[11.5px]">₹{formatPaise(value)}</span><Status value={row.status} />
      <div className="flex justify-end gap-1">{row.status === 'draft' && <><Button variant="ghost" onClick={() => onStatus(row, 'cancelled')}>Cancel</Button><Button data-testid={`issue-order-${row.id}`} variant="primary" disabled={busyKey === `po-${row.id}`} onClick={() => onStatus(row, 'issued')}>Issue order</Button></>}{['issued', 'part_received'].includes(row.status) && <><Button variant="ghost" onClick={() => onStatus(row, 'closed')}>Close</Button><Button data-testid={`receive-order-${row.id}`} variant="primary" onClick={() => onReceive(row)}><Truck size={14} /> Receive</Button></>}</div>
    </div>})}
  </Panel>
}

function ReceiptList({ rows, loading, onVoucher }: { rows: GoodsReceipt[]; loading: boolean; onVoucher: (id: number) => void }): React.JSX.Element {
  if (!loading && !rows.length) return <EmptyState title="No goods receipts" hint="Issue a purchase order first, then record inspected quantities when the delivery arrives." />
  return <Panel><div className="grid grid-cols-[120px_120px_90px_1fr_140px_160px] border-b border-line bg-panel2 px-3 py-2 text-[9.5px] font-semibold uppercase tracking-[0.08em] text-muted"><span>GRN</span><span>Purchase order</span><span>Date</span><span>Inspection result</span><span>Status</span><span className="text-right">Inventory link</span></div>
    {rows.map((row) => <div key={row.id} data-testid={`goods-receipt-${row.id}`} className="grid grid-cols-[120px_120px_90px_1fr_140px_160px] items-center border-b border-line px-3 py-2.5 last:border-0"><div><b className="text-[12px]">{row.number}</b><p className="text-[9.5px] text-muted">{row.receivedBy}</p></div><span className="text-[11.5px]">{row.purchaseOrderNumber}</span><span className="num text-[10.5px] text-muted">{toDisplayDate(row.date)}</span><div className="text-[11px]">{row.lines.map((line) => <span key={line.id} className="mr-3 inline-flex gap-1"><b>{line.itemName}</b><span className="text-dr">{qty(line.qtyAcceptedMilli, line.unitSymbol)} accepted</span>{line.qtyRejectedMilli > 0 && <span className="text-cr">· {qty(line.qtyRejectedMilli)} rejected</span>}</span>)}</div><Status value={row.status} /><div className="text-right"><Button variant="ghost" onClick={() => onVoucher(row.inventoryVoucherId)}>Open stock voucher</Button></div></div>)}
  </Panel>
}

function RequisitionModal({ onClose, onSaved }: { onClose: () => void; onSaved: (row: PurchaseRequisition) => Promise<void> }): React.JSX.Element {
  const toast = useToasts(); const workingDate = useSession((state) => state.workingDate)
  const [date, setDate] = useState(workingDate || todayISO()); const [neededBy, setNeededBy] = useState<string | null>(null); const [department, setDepartment] = useState(''); const [note, setNote] = useState(''); const [saving, setSaving] = useState(false)
  const [lines, setLines] = useState<ReqLineDraft[]>([{ key: 1, stockItemId: null, qty: '', note: '' }])
  const issues = [...(lines.some((line) => line.stockItemId == null) ? ['Choose an item on every line'] : []), ...(lines.some((line) => parseQty(line.qty) == null) ? ['Enter a positive quantity (up to three decimals) on every line'] : []), ...(new Set(lines.map((line) => line.stockItemId).filter(Boolean)).size !== lines.filter((line) => line.stockItemId).length ? ['Each item can appear only once'] : [])]
  const patchLine = (key: number, patch: Partial<ReqLineDraft>): void => setLines((current) => current.map((line) => line.key === key ? { ...line, ...patch } : line))
  const save = async (): Promise<void> => { if (issues.length || saving) return; setSaving(true); try { await onSaved(await api.procurement.createRequisition({ date, neededBy, department: department.trim() || null, note: note.trim() || null, lines: lines.map((line) => ({ stockItemId: line.stockItemId!, qtyMilli: parseQty(line.qty)!, note: line.note.trim() || null })) })) } catch (error) { toast.push('error', error instanceof Error ? error.message : String(error)); setSaving(false) } }
  return <Modal title="New purchase requisition" onClose={onClose} dirty wide><div className="grid gap-4"><div className="grid grid-cols-3 gap-3"><Field label="Request date"><DateInput value={date} context={workingDate} onChange={setDate} testId="input-requisition-date" /></Field><Field label="Needed by" hint="Optional"><div className="flex gap-1"><DateInput value={neededBy ?? date} context={date} onChange={setNeededBy} testId="input-requisition-needed" />{neededBy && <Button variant="ghost" onClick={() => setNeededBy(null)}>Clear</Button>}</div></Field><Field label="Department / cost owner"><TextInput value={department} maxLength={120} placeholder="Production" onChange={(event) => setDepartment(event.target.value)} /></Field></div>
    <Panel><div className="grid grid-cols-[36px_1fr_150px_1fr_38px] border-b border-line bg-panel2 px-2 py-2 text-[9.5px] font-semibold uppercase tracking-[0.08em] text-muted"><span>#</span><span>Stock item</span><span>Quantity</span><span>Purpose / specification</span><span /></div>{lines.map((line, index) => <div key={line.key} className="grid grid-cols-[36px_1fr_150px_1fr_38px] items-start gap-2 border-b border-line px-2 py-2 last:border-0"><span className="num pt-2 text-[10px] text-muted">{index + 1}</span><ItemPicker testId={`picker-requisition-item-${index}`} value={line.stockItemId} onPick={(id) => patchLine(line.key, { stockItemId: id })} /><TextInput data-testid={`input-requisition-qty-${index}`} className="num text-right" value={line.qty} inputMode="decimal" placeholder="0.000" onChange={(event) => patchLine(line.key, { qty: event.target.value })} /><TextInput value={line.note} maxLength={300} placeholder="Why it is needed" onChange={(event) => patchLine(line.key, { note: event.target.value })} /><Button aria-label="Remove line" variant="ghost" disabled={lines.length === 1} onClick={() => setLines((current) => current.filter((entry) => entry.key !== line.key))}>×</Button></div>)}<div className="border-t border-line px-2 py-2"><Button variant="ghost" onClick={() => setLines((current) => [...current, { key: Math.max(...current.map((line) => line.key)) + 1, stockItemId: null, qty: '', note: '' }])}><Plus size={13} /> Add item</Button></div></Panel>
    <Field label="Request note"><TextInput value={note} maxLength={1000} placeholder="Context for the approver" onChange={(event) => setNote(event.target.value)} /></Field><ValidationSummary issues={issues} /><div className="flex items-center justify-between"><p className="text-[10.5px] text-muted">Saving creates a draft request. It does not reserve stock or affect accounts.</p><div className="flex gap-2"><Button onClick={onClose}>Cancel</Button><Button data-testid="save-requisition" variant="primary" disabled={saving || issues.length > 0} onClick={() => void save()}>{saving ? 'Saving…' : 'Save draft'}</Button></div></div></div></Modal>
}

function OrderModal({ source, onClose, onSaved }: { source: PurchaseRequisition | null; onClose: () => void; onSaved: (row: PurchaseOrder) => Promise<void> }): React.JSX.Element {
  const toast = useToasts(); const workingDate = useSession((state) => state.workingDate); const [date, setDate] = useState(workingDate || todayISO()); const [expectedDate, setExpectedDate] = useState<string | null>(source?.neededBy ?? null); const [supplierLedgerId, setSupplierLedgerId] = useState<number | null>(null); const [note, setNote] = useState(source?.note ?? ''); const [saving, setSaving] = useState(false)
  const [lines, setLines] = useState<OrderLineDraft[]>(source ? source.lines.map((line, index) => ({ key: index + 1, stockItemId: line.stockItemId, qty: String(line.qtyMilli / 1000), ratePaise: null, gstRate: '' })) : [{ key: 1, stockItemId: null, qty: '', ratePaise: null, gstRate: '' }])
  const issues = [...(supplierLedgerId == null ? ['Choose a supplier ledger'] : []), ...(lines.some((line) => line.stockItemId == null) ? ['Choose an item on every line'] : []), ...(lines.some((line) => parseQty(line.qty) == null) ? ['Enter a positive quantity on every line'] : []), ...(lines.some((line) => line.ratePaise == null || line.ratePaise < 0) ? ['Enter a valid rate on every line'] : []), ...(lines.some((line) => line.gstRate.trim() === '' || Number(line.gstRate) < 0 || Number(line.gstRate) > 100) ? ['Enter GST from 0 to 100 on every line'] : [])]
  const patchLine = (key: number, patch: Partial<OrderLineDraft>): void => setLines((current) => current.map((line) => line.key === key ? { ...line, ...patch } : line))
  const subtotal = lines.reduce((sum, line) => sum + (parseQty(line.qty) && line.ratePaise != null ? Math.round(parseQty(line.qty)! * line.ratePaise / 1000) : 0), 0)
  const tax = lines.reduce((sum, line) => { const base = parseQty(line.qty) && line.ratePaise != null ? Math.round(parseQty(line.qty)! * line.ratePaise / 1000) : 0; return sum + Math.round(base * (Number(line.gstRate) || 0) / 100) }, 0)
  const save = async (): Promise<void> => { if (issues.length || saving) return; setSaving(true); try { await onSaved(await api.procurement.createOrder({ date, expectedDate, supplierLedgerId: supplierLedgerId!, requisitionId: source?.id ?? null, note: note.trim() || null, lines: lines.map((line) => ({ stockItemId: line.stockItemId!, qtyMilli: parseQty(line.qty)!, ratePaise: line.ratePaise!, gstRate: Number(line.gstRate) })) })) } catch (error) { toast.push('error', error instanceof Error ? error.message : String(error)); setSaving(false) } }
  return <Modal title={source ? `Create PO from ${source.number}` : 'New purchase order'} onClose={onClose} dirty wide><div className="grid gap-4"><div className="grid grid-cols-3 gap-3"><Field label="Supplier"><LedgerPicker value={supplierLedgerId} onPick={setSupplierLedgerId} placeholder="Supplier ledger" autoFocus testId="picker-order-supplier" /></Field><Field label="Order date"><DateInput value={date} context={workingDate} onChange={setDate} testId="input-order-date" /></Field><Field label="Expected delivery" hint="Optional"><DateInput value={expectedDate ?? date} context={date} onChange={setExpectedDate} testId="input-order-expected" /></Field></div>
    {source && <div className="rounded-md border border-dr/20 bg-dr/5 px-3 py-2 text-[11px]"><CheckCircle size={15} className="mr-1 inline text-dr" />Approved demand from <b>{source.department || source.requestedBy}</b> is locked into this order’s item quantities.</div>}
    <Panel><div className="grid grid-cols-[36px_1fr_120px_150px_90px_130px_38px] border-b border-line bg-panel2 px-2 py-2 text-[9.5px] font-semibold uppercase tracking-[0.08em] text-muted"><span>#</span><span>Item</span><span>Quantity</span><span>Rate / unit</span><span>GST %</span><span className="text-right">Line value</span><span /></div>{lines.map((line, index) => { const amount = parseQty(line.qty) && line.ratePaise != null ? Math.round(parseQty(line.qty)! * line.ratePaise / 1000) : 0; return <div key={line.key} className="grid grid-cols-[36px_1fr_120px_150px_90px_130px_38px] items-start gap-2 border-b border-line px-2 py-2 last:border-0"><span className="num pt-2 text-[10px] text-muted">{index + 1}</span><ItemPicker testId={`picker-order-item-${index}`} value={line.stockItemId} onPick={(id) => patchLine(line.key, { stockItemId: id })} /><TextInput data-testid={`input-order-qty-${index}`} className="num text-right" value={line.qty} inputMode="decimal" onChange={(event) => patchLine(line.key, { qty: event.target.value })} /><AmountInput testId={`input-order-rate-${index}`} paise={line.ratePaise} onPaise={(value) => patchLine(line.key, { ratePaise: value })} /><TextInput data-testid={`input-order-gst-${index}`} className="num text-right" value={line.gstRate} inputMode="decimal" placeholder="18" onChange={(event) => patchLine(line.key, { gstRate: event.target.value })} /><span className="num pt-2 text-right text-[11px]">₹{formatPaise(amount)}</span><Button variant="ghost" disabled={!!source || lines.length === 1} onClick={() => setLines((current) => current.filter((entry) => entry.key !== line.key))}>×</Button></div>})}{!source && <div className="border-t border-line px-2 py-2"><Button variant="ghost" onClick={() => setLines((current) => [...current, { key: Math.max(...current.map((line) => line.key)) + 1, stockItemId: null, qty: '', ratePaise: null, gstRate: '' }])}><Plus size={13} /> Add item</Button></div>}</Panel>
    <div className="grid grid-cols-[1fr_260px] gap-4"><Field label="Commercial note"><TextInput value={note} maxLength={1000} placeholder="Terms, specification or delivery instruction" onChange={(event) => setNote(event.target.value)} /></Field><Panel className="px-3 py-2"><div className="flex justify-between text-[11px] text-muted"><span>Subtotal</span><span className="num">₹{formatPaise(subtotal)}</span></div><div className="mt-1 flex justify-between text-[11px] text-muted"><span>Indicative GST</span><span className="num">₹{formatPaise(tax)}</span></div><div className="mt-2 flex justify-between border-t border-line pt-2 text-[12px] font-semibold"><span>Order total</span><span className="num">₹{formatPaise(subtotal + tax)}</span></div></Panel></div><ValidationSummary issues={issues} /><div className="flex items-center justify-between"><p className="text-[10.5px] text-muted">The draft must be issued before a warehouse can receive against it.</p><div className="flex gap-2"><Button onClick={onClose}>Cancel</Button><Button data-testid="save-purchase-order" variant="primary" disabled={saving || issues.length > 0} onClick={() => void save()}>{saving ? 'Saving…' : 'Save draft PO'}</Button></div></div></div></Modal>
}

function ReceiptModal({ order, onClose, onSaved }: { order: PurchaseOrder; onClose: () => void; onSaved: (row: GoodsReceipt) => Promise<void> }): React.JSX.Element {
  const toast = useToasts(); const workingDate = useSession((state) => state.workingDate); const [date, setDate] = useState(workingDate || todayISO()); const [note, setNote] = useState(''); const [saving, setSaving] = useState(false)
  const eligible = useMemo(() => order.lines.filter((line) => line.outstandingQtyMilli > 0), [order])
  const [values, setValues] = useState(() => new Map(eligible.map((line) => [line.id, { received: String(line.outstandingQtyMilli / 1000), accepted: String(line.outstandingQtyMilli / 1000), rejected: '0' }])))
  const parsed = eligible.map((line) => { const value = values.get(line.id)!; return { line, received: parseQty(value.received), accepted: value.accepted.trim() === '0' ? 0 : parseQty(value.accepted), rejected: value.rejected.trim() === '0' ? 0 : parseQty(value.rejected) } })
  const issues = [...(parsed.some((row) => row.received == null || row.accepted == null || row.rejected == null) ? ['Enter valid non-negative inspected quantities'] : []), ...(parsed.some((row) => row.received != null && row.accepted != null && row.rejected != null && row.accepted + row.rejected !== row.received) ? ['Each received quantity must equal accepted plus rejected'] : []), ...(parsed.some((row) => (row.accepted ?? 0) > row.line.outstandingQtyMilli) ? ['Accepted quantity cannot exceed the order balance'] : []), ...(parsed.reduce((sum, row) => sum + (row.accepted ?? 0), 0) <= 0 ? ['Accept at least one quantity to post this GRN'] : [])]
  const patch = (id: number, field: 'received' | 'accepted' | 'rejected', value: string): void => setValues((current) => { const next = new Map(current); next.set(id, { ...next.get(id)!, [field]: value }); return next })
  const save = async (): Promise<void> => { if (issues.length || saving) return; setSaving(true); try { await onSaved(await api.procurement.createReceipt({ purchaseOrderId: order.id, date, note: note.trim() || null, lines: parsed.map((row) => ({ purchaseOrderLineId: row.line.id, qtyReceivedMilli: row.received!, qtyAcceptedMilli: row.accepted!, qtyRejectedMilli: row.rejected! })) })) } catch (error) { toast.push('error', error instanceof Error ? error.message : String(error)); setSaving(false) } }
  return <Modal title={`Receive goods · ${order.number}`} onClose={onClose} dirty wide><div className="grid gap-4"><div className="grid grid-cols-[1fr_190px] gap-3 rounded-md border border-line bg-panel2 px-3 py-2"><div><p className="text-[12px] font-semibold">{order.supplierName}</p><p className="mt-0.5 text-[10.5px] text-muted">Inspect the physical delivery. Only accepted quantity increases stock; rejected quantity stays visible against the order.</p></div><Field label="Receipt date"><DateInput value={date} context={workingDate} onChange={setDate} testId="input-receipt-date" /></Field></div>
    <Panel><div className="grid grid-cols-[1fr_130px_130px_130px_130px] border-b border-line bg-panel2 px-3 py-2 text-[9.5px] font-semibold uppercase tracking-[0.08em] text-muted"><span>Item</span><span className="text-right">Order balance</span><span className="text-right">Delivered</span><span className="text-right text-dr">Accepted</span><span className="text-right text-cr">Rejected</span></div>{eligible.map((line, index) => { const value = values.get(line.id)!; return <div key={line.id} className="grid grid-cols-[1fr_130px_130px_130px_130px] items-center gap-2 border-b border-line px-3 py-2.5 last:border-0"><div><b className="text-[11.5px]">{line.itemName}</b><p className="text-[9.5px] text-muted">Ordered {qty(line.qtyOrderedMilli, line.unitSymbol)} · previously accepted {qty(line.qtyAcceptedMilli)}</p></div><span className="num text-right text-[11px]">{qty(line.outstandingQtyMilli)}</span><TextInput data-testid={`input-receipt-delivered-${index}`} className="num text-right" value={value.received} onChange={(event) => patch(line.id, 'received', event.target.value)} /><TextInput data-testid={`input-receipt-accepted-${index}`} className="num border-dr/25 text-right" value={value.accepted} onChange={(event) => patch(line.id, 'accepted', event.target.value)} /><TextInput data-testid={`input-receipt-rejected-${index}`} className="num border-cr/25 text-right" value={value.rejected} onChange={(event) => patch(line.id, 'rejected', event.target.value)} /></div>})}</Panel>
    <div className="grid grid-cols-[1fr_300px] gap-3"><Field label="Inspection note"><TextInput value={note} maxLength={1000} placeholder="Delivery challan, damage or quality notes" onChange={(event) => setNote(event.target.value)} /></Field><div className="rounded-md border border-amber/25 bg-amber/5 px-3 py-2 text-[10.5px]"><WarningCircle size={15} className="mr-1 inline text-amber" /><b>Posting boundary:</b> this creates a stock journal for accepted goods. It does not create a supplier invoice or payable.</div></div><ValidationSummary issues={issues} /><div className="flex justify-end gap-2"><Button onClick={onClose}>Cancel</Button><Button data-testid="post-goods-receipt" variant="primary" disabled={saving || issues.length > 0} onClick={() => void save()}>{saving ? 'Posting…' : 'Post GRN & stock'}</Button></div></div></Modal>
}
