import type { DB } from '../db/connection'
import type { DiscountActorRole, DiscountAuthorityResult, SalesDiscountPolicy, SalesDiscountPolicyInput } from '@shared/salesBilling'
import { writeAudit } from './audit'

interface Row{id:number;name:string;scope_kind:SalesDiscountPolicy['scopeKind'];role:DiscountActorRole|null;stock_item_id:number|null;customer_ledger_id:number|null;max_discount_bps:number;active:number;created_by:string;created_at:string;updated_at:string;item_name:string|null;customer_name:string|null}
const SELECT=`SELECT p.*,si.name AS item_name,l.name AS customer_name FROM sales_discount_policies p LEFT JOIN stock_items si ON si.id=p.stock_item_id LEFT JOIN ledgers l ON l.id=p.customer_ledger_id`
function map(row:Row):SalesDiscountPolicy{return{id:row.id,name:row.name,scopeKind:row.scope_kind,role:row.role,stockItemId:row.stock_item_id,customerLedgerId:row.customer_ledger_id,maxDiscountBps:row.max_discount_bps,active:!!row.active,createdBy:row.created_by,createdAt:row.created_at,updatedAt:row.updated_at,scopeLabel:row.scope_kind==='global'?'All sales':row.scope_kind==='role'?`Role: ${row.role}`:row.scope_kind==='item'?`Item: ${row.item_name??'Missing'}`:`Customer: ${row.customer_name??'Missing'}`}}
export function listDiscountPolicies(db:DB):SalesDiscountPolicy[]{return(db.prepare(`${SELECT} ORDER BY p.active DESC,p.scope_kind,p.name`).all() as Row[]).map(map)}
function validate(input:SalesDiscountPolicyInput):void{const valid=input.scopeKind==='global'&&!input.role&&!input.stockItemId&&!input.customerLedgerId||input.scopeKind==='role'&&!!input.role&&!input.stockItemId&&!input.customerLedgerId||input.scopeKind==='item'&&!input.role&&!!input.stockItemId&&!input.customerLedgerId||input.scopeKind==='customer'&&!input.role&&!input.stockItemId&&!!input.customerLedgerId;if(!valid)throw new Error('Discount policy scope is incomplete');if(input.maxDiscountBps<0||input.maxDiscountBps>10000)throw new Error('Maximum discount must be between 0% and 100%')}
export function saveDiscountPolicy(db:DB,input:SalesDiscountPolicyInput,author:string,id?:number):SalesDiscountPolicy{validate(input);const actor=author.trim()||'Local user',name=input.name.trim();if(!name)throw new Error('Policy name is required');let policyId=id;if(id){const before=listDiscountPolicies(db).find((row)=>row.id===id);if(!before)throw new Error('Discount policy was not found');db.prepare(`UPDATE sales_discount_policies SET name=?,scope_kind=?,role=?,stock_item_id=?,customer_ledger_id=?,max_discount_bps=?,active=?,updated_at=datetime('now') WHERE id=?`).run(name,input.scopeKind,input.role,input.stockItemId,input.customerLedgerId,input.maxDiscountBps,Number(input.active),id);writeAudit(db,'sales_discount_policy',id,'update',before,input)}else{policyId=Number(db.prepare(`INSERT INTO sales_discount_policies(name,scope_kind,role,stock_item_id,customer_ledger_id,max_discount_bps,active,created_by) VALUES(?,?,?,?,?,?,?,?)`).run(name,input.scopeKind,input.role,input.stockItemId,input.customerLedgerId,input.maxDiscountBps,Number(input.active),actor).lastInsertRowid);writeAudit(db,'sales_discount_policy',policyId,'create',null,input)}return listDiscountPolicies(db).find((row)=>row.id===policyId)!}

export function discountAuthority(db:DB,role:DiscountActorRole,customerLedgerId:number|null,stockItemId:number|null,requestedDiscountBps:number):DiscountAuthorityResult{
  const policies=listDiscountPolicies(db).filter((policy)=>policy.active&&(policy.scopeKind==='global'||policy.scopeKind==='role'&&policy.role===role||policy.scopeKind==='item'&&policy.stockItemId===stockItemId||policy.scopeKind==='customer'&&policy.customerLedgerId===customerLedgerId));const max=policies.length?Math.min(...policies.map((policy)=>policy.maxDiscountBps)):10000;return{allowed:requestedDiscountBps<=max,requestedDiscountBps,maxDiscountBps:max,policyNames:policies.filter((policy)=>policy.maxDiscountBps===max).map((policy)=>policy.name)}}

export function assertDiscountAuthority(db:DB,args:{role:DiscountActorRole;actorName:string;customerLedgerId:number|null;contextKind:'sales_document'|'sales_invoice';lines:Array<{stockItemId:number|null;requestedDiscountBps:number}>}):void{
  for(const line of args.lines){const result=discountAuthority(db,args.role,args.customerLedgerId,line.stockItemId,resultSafe(line.requestedDiscountBps));if(!result.allowed){db.prepare(`INSERT INTO sales_discount_events(context_kind,customer_ledger_id,stock_item_id,requested_discount_bps,allowed_discount_bps,actor_role,actor_name,outcome) VALUES(?,?,?,?,?,?,?,'blocked')`).run(args.contextKind,args.customerLedgerId,line.stockItemId,result.requestedDiscountBps,result.maxDiscountBps,args.role,args.actorName);throw new Error(`Discount ${formatBps(result.requestedDiscountBps)} exceeds the ${formatBps(result.maxDiscountBps)} authority limit${result.policyNames.length?` (${result.policyNames.join(', ')})`:''}`)}}
}
function resultSafe(value:number):number{return Number.isFinite(value)?Math.max(0,Math.round(value)):0}
function formatBps(value:number):string{return`${(value/100).toFixed(value%100?2:0)}%`}

export function invoiceDiscountBps(qtyMilli:number,rate:number,discount:number):number{const gross=Math.round(qtyMilli*rate/1000);return gross>0?Math.ceil(discount*10000/gross):0}
