import type { DB } from '../db/connection'
import type {
  ManagementScenario, ManagementScenarioInput, ReportAnnotation, ScenarioProjection,
  ScheduleIiiMapping, ScheduleIiiStatement, VarianceDriver, VarianceExplanation
} from '@shared/management'
import { IN_BOOKS } from './vouchers'
import { dashboard, profitAndLoss } from './reports'
import { writeAudit } from './audit'

interface PartyAggregate { id: number; name: string; amount: number; voucherIds: string }

function partyAggregates(db: DB, kind: 'sales' | 'purchase', from: string, to: string): PartyAggregate[] {
  const side = kind === 'sales' ? 'dr' : 'cr'
  return db.prepare(
    `SELECT p.id,p.name,COALESCE(SUM(vl.amount),0) AS amount,GROUP_CONCAT(DISTINCT v.id) AS voucherIds
     FROM vouchers v JOIN voucher_types vt ON vt.id=v.voucher_type_id
     JOIN ledgers p ON p.id=v.party_ledger_id
     JOIN voucher_lines vl ON vl.voucher_id=v.id AND vl.ledger_id=p.id AND vl.dr_cr=?
     WHERE vt.kind=? AND v.date BETWEEN ? AND ? AND ${IN_BOOKS}
     GROUP BY p.id,p.name`
  ).all(side, kind, from, to) as PartyAggregate[]
}

interface ItemAggregate { id: number; name: string; amount: number; qtyMilli: number; voucherIds: string }
function itemAggregates(db: DB, from: string, to: string): ItemAggregate[] {
  return db.prepare(
    `SELECT si.id,si.name,SUM(il.amount) AS amount,SUM(il.qty_milli) AS qtyMilli,
      GROUP_CONCAT(DISTINCT v.id) AS voucherIds
     FROM inventory_lines il JOIN vouchers v ON v.id=il.voucher_id
     JOIN voucher_types vt ON vt.id=v.voucher_type_id JOIN stock_items si ON si.id=il.stock_item_id
     WHERE vt.kind='sales' AND il.direction='out' AND v.date BETWEEN ? AND ? AND ${IN_BOOKS}
     GROUP BY si.id,si.name`
  ).all(from, to) as ItemAggregate[]
}

const idsOf = (csv?: string): number[] => csv ? [...new Set(csv.split(',').map(Number).filter(Number.isFinite))] : []

export function varianceExplanation(db: DB, currentFrom: string, currentTo: string, comparisonFrom: string, comparisonTo: string): VarianceExplanation {
  const drivers: VarianceDriver[] = []
  for (const [dimension, kind] of [['customer','sales'],['supplier','purchase']] as const) {
    const current=partyAggregates(db,kind,currentFrom,currentTo);const comparison=partyAggregates(db,kind,comparisonFrom,comparisonTo)
    const keys=new Set([...current.map((row)=>row.id),...comparison.map((row)=>row.id)])
    for(const id of keys){const a=current.find((row)=>row.id===id);const b=comparison.find((row)=>row.id===id);const currentValue=a?.amount??0;const comparisonValue=b?.amount??0
      drivers.push({key:`${dimension}:${id}`,dimension,name:a?.name??b?.name??`#${id}`,current:currentValue,comparison:comparisonValue,change:currentValue-comparisonValue,currentQtyMilli:null,comparisonQtyMilli:null,priceImpact:null,quantityImpact:null,timingResidual:null,voucherIds:[...new Set([...idsOf(a?.voucherIds),...idsOf(b?.voucherIds)])]})}
  }
  const currentItems=itemAggregates(db,currentFrom,currentTo);const comparisonItems=itemAggregates(db,comparisonFrom,comparisonTo)
  for(const id of new Set([...currentItems.map((row)=>row.id),...comparisonItems.map((row)=>row.id)])){const a=currentItems.find((row)=>row.id===id);const b=comparisonItems.find((row)=>row.id===id);const current=a?.amount??0;const comparison=b?.amount??0;const currentQty=a?.qtyMilli??0;const comparisonQty=b?.qtyMilli??0;const priorRate=comparisonQty?comparison*1000/comparisonQty:0;const currentRate=currentQty?current*1000/currentQty:priorRate;const priceImpact=Math.round((currentRate-priorRate)*currentQty/1000);const quantityImpact=Math.round((currentQty-comparisonQty)*priorRate/1000);const change=current-comparison
    drivers.push({key:`item:${id}`,dimension:'item',name:a?.name??b?.name??`#${id}`,current,comparison,change,currentQtyMilli:currentQty,comparisonQtyMilli:comparisonQty,priceImpact,quantityImpact,timingResidual:change-priceImpact-quantityImpact,voucherIds:[...new Set([...idsOf(a?.voucherIds),...idsOf(b?.voucherIds)])]})}
  const sum=(dimension:'customer'|'supplier')=>drivers.filter((row)=>row.dimension===dimension).reduce((total,row)=>total+row.change,0)
  return {current:{from:currentFrom,to:currentTo},comparison:{from:comparisonFrom,to:comparisonTo},salesChange:sum('customer'),purchaseChange:sum('supplier'),drivers:drivers.sort((a,b)=>Math.abs(b.change)-Math.abs(a.change))}
}

function mapScenario(row: Record<string,unknown>): ManagementScenario { return {id:Number(row.id),name:String(row.name),salesGrowthPct:Number(row.salesGrowthPct),grossMarginPct:row.grossMarginPct==null?null:Number(row.grossMarginPct),expenseChangePct:Number(row.expenseChangePct),collectionDaysChange:Number(row.collectionDaysChange),paymentDaysChange:Number(row.paymentDaysChange),note:row.note==null?null:String(row.note),createdBy:String(row.createdBy),createdAt:String(row.createdAt),updatedAt:String(row.updatedAt)} }
export function listManagementScenarios(db: DB): ManagementScenario[]{return (db.prepare(`SELECT id,name,sales_growth_pct AS salesGrowthPct,gross_margin_pct AS grossMarginPct,expense_change_pct AS expenseChangePct,collection_days_change AS collectionDaysChange,payment_days_change AS paymentDaysChange,note,created_by AS createdBy,created_at AS createdAt,updated_at AS updatedAt FROM management_scenarios ORDER BY updated_at DESC,name`).all() as Record<string,unknown>[]).map(mapScenario)}
export function saveManagementScenario(db:DB,input:ManagementScenarioInput,actor:string,id?:number):ManagementScenario{const before=id?listManagementScenarios(db).find((row)=>row.id===id):null;if(id&&!before)throw new Error('Management scenario not found');let saved=id;if(id)db.prepare(`UPDATE management_scenarios SET name=?,sales_growth_pct=?,gross_margin_pct=?,expense_change_pct=?,collection_days_change=?,payment_days_change=?,note=?,updated_at=datetime('now') WHERE id=?`).run(input.name.trim(),input.salesGrowthPct,input.grossMarginPct,input.expenseChangePct,input.collectionDaysChange,input.paymentDaysChange,input.note?.trim()||null,id);else saved=Number(db.prepare(`INSERT INTO management_scenarios(name,sales_growth_pct,gross_margin_pct,expense_change_pct,collection_days_change,payment_days_change,note,created_by) VALUES(?,?,?,?,?,?,?,?)`).run(input.name.trim(),input.salesGrowthPct,input.grossMarginPct,input.expenseChangePct,input.collectionDaysChange,input.paymentDaysChange,input.note?.trim()||null,actor).lastInsertRowid);const after=listManagementScenarios(db).find((row)=>row.id===saved)!;writeAudit(db,'management_scenario',after.id,before?'update':'create',before,after);return after}
export function deleteManagementScenario(db:DB,id:number):void{const before=listManagementScenarios(db).find((row)=>row.id===id);if(!before)throw new Error('Management scenario not found');db.prepare('DELETE FROM management_scenarios WHERE id=?').run(id);writeAudit(db,'management_scenario',id,'delete',before,null)}

export function scenarioProjection(db:DB,from:string,to:string,input:ManagementScenarioInput):ScenarioProjection{const pnl=profitAndLoss(db,from,to);const dash=dashboard(db,to,from);const sales=pnl.tradingIncomes.reduce((sum,row)=>sum+row.amount,0);const grossMargin=sales?100*pnl.grossProfit/sales:0;const targetMargin=input.grossMarginPct??grossMargin;const projectedSales=Math.round(sales*(100+input.salesGrowthPct)/100);const projectedGross=Math.round(projectedSales*targetMargin/100);const baseIndirectExpense=pnl.indirectExpenses.reduce((sum,row)=>sum+row.amount,0);const projectedExpense=Math.round(baseIndirectExpense*(100+input.expenseChangePct)/100);const indirectIncome=pnl.indirectIncomes.reduce((sum,row)=>sum+row.amount,0);const periodDays=Math.max(1,Math.round((Date.parse(to)-Date.parse(from))/86400000)+1);const receivableFactor=Math.max(0,periodDays+input.collectionDaysChange)/periodDays;const payableFactor=Math.max(0,periodDays+input.paymentDaysChange)/periodDays;return{scenario:input,base:{sales,grossProfit:pnl.grossProfit,netProfit:pnl.netProfit,receivables:dash.receivables,payables:dash.payables},projected:{sales:projectedSales,grossProfit:projectedGross,netProfit:projectedGross+indirectIncome-projectedExpense,receivables:Math.round(dash.receivables*(projectedSales/(sales||projectedSales||1))*receivableFactor),payables:Math.round(dash.payables*payableFactor)},assumptions:[`Sales ${input.salesGrowthPct>=0?'+':''}${input.salesGrowthPct}%`,`Gross margin ${targetMargin.toFixed(1)}%`,`Indirect expenses ${input.expenseChangePct>=0?'+':''}${input.expenseChangePct}%`,`Collection timing ${input.collectionDaysChange>=0?'+':''}${input.collectionDaysChange} days`,`Payment timing ${input.paymentDaysChange>=0?'+':''}${input.paymentDaysChange} days`]}}

function mapAnnotation(row:Record<string,unknown>):ReportAnnotation{return{id:Number(row.id),reportKey:String(row.reportKey),rowKey:String(row.rowKey),from:String(row.from),to:String(row.to),note:String(row.note),includeInExport:!!row.includeInExport,author:String(row.author),createdAt:String(row.createdAt),updatedAt:String(row.updatedAt)}}
export function listReportAnnotations(db:DB,reportKey:string,from:string,to:string):ReportAnnotation[]{return(db.prepare(`SELECT id,report_key AS reportKey,row_key AS rowKey,from_date AS 'from',to_date AS 'to',note,include_in_export AS includeInExport,author,created_at AS createdAt,updated_at AS updatedAt FROM report_annotations WHERE report_key=? AND from_date=? AND to_date=? ORDER BY row_key`).all(reportKey,from,to) as Record<string,unknown>[]).map(mapAnnotation)}
export function saveReportAnnotation(db:DB,input:{reportKey:string;rowKey:string;from:string;to:string;note:string;includeInExport:boolean},actor:string):ReportAnnotation{const before=listReportAnnotations(db,input.reportKey,input.from,input.to).find((row)=>row.rowKey===input.rowKey)??null;db.prepare(`INSERT INTO report_annotations(report_key,row_key,from_date,to_date,note,include_in_export,author) VALUES(?,?,?,?,?,?,?) ON CONFLICT(report_key,row_key,from_date,to_date) DO UPDATE SET note=excluded.note,include_in_export=excluded.include_in_export,author=excluded.author,updated_at=datetime('now')`).run(input.reportKey,input.rowKey,input.from,input.to,input.note.trim(),input.includeInExport?1:0,actor);const after=listReportAnnotations(db,input.reportKey,input.from,input.to).find((row)=>row.rowKey===input.rowKey)!;writeAudit(db,'report_annotation',after.id,before?'update':'create',before,after);return after}

export function listScheduleIiiMappings(db:DB):ScheduleIiiMapping[]{return db.prepare(`SELECT m.id,m.group_id AS groupId,g.name AS groupName,m.side,m.section,m.note_code AS noteCode,m.sort_order AS sortOrder,m.updated_by AS updatedBy,m.updated_at AS updatedAt FROM schedule_iii_mappings m JOIN groups g ON g.id=m.group_id ORDER BY m.side,m.sort_order,m.section,g.name`).all() as ScheduleIiiMapping[]}
export function saveScheduleIiiMapping(db:DB,input:Omit<ScheduleIiiMapping,'id'|'groupName'|'updatedBy'|'updatedAt'>,actor:string):ScheduleIiiMapping{const group=db.prepare('SELECT id FROM groups WHERE id=?').get(input.groupId);if(!group)throw new Error('Account group not found');const before=listScheduleIiiMappings(db).find((row)=>row.groupId===input.groupId)??null;db.prepare(`INSERT INTO schedule_iii_mappings(group_id,side,section,note_code,sort_order,updated_by) VALUES(?,?,?,?,?,?) ON CONFLICT(group_id) DO UPDATE SET side=excluded.side,section=excluded.section,note_code=excluded.note_code,sort_order=excluded.sort_order,updated_by=excluded.updated_by,updated_at=datetime('now')`).run(input.groupId,input.side,input.section.trim(),input.noteCode?.trim()||null,input.sortOrder,actor);const after=listScheduleIiiMappings(db).find((row)=>row.groupId===input.groupId)!;writeAudit(db,'schedule_iii_mapping',after.id,before?'update':'create',before,after);return after}

function groupBalances(db:DB,asOn:string):Map<number,number>{const rows=db.prepare(`SELECT l.group_id AS groupId,SUM(l.opening_balance+COALESCE(m.amount,0)) AS amount FROM ledgers l LEFT JOIN(SELECT vl.ledger_id,SUM(CASE WHEN vl.dr_cr='dr' THEN vl.amount ELSE -vl.amount END) AS amount FROM voucher_lines vl JOIN vouchers v ON v.id=vl.voucher_id WHERE v.date<=? AND ${IN_BOOKS} GROUP BY vl.ledger_id)m ON m.ledger_id=l.id GROUP BY l.group_id`).all(asOn) as {groupId:number;amount:number}[];return new Map(rows.map((row)=>[row.groupId,row.amount]))}
export function scheduleIiiStatement(db:DB,asOn:string,priorAsOn:string):ScheduleIiiStatement{const mappings=listScheduleIiiMappings(db);const current=groupBalances(db,asOn);const prior=groupBalances(db,priorAsOn);const groups=db.prepare('SELECT id,name,nature FROM groups').all() as {id:number;name:string;nature:string}[];const rows=[] as ScheduleIiiStatement['rows'];for(const mapping of mappings){let row=rows.find((item)=>item.side===mapping.side&&item.section===mapping.section&&item.noteCode===mapping.noteCode);if(!row){row={side:mapping.side,section:mapping.section,noteCode:mapping.noteCode,current:0,prior:0,groupIds:[],voucherIds:[]};rows.push(row)}const sign=mapping.side==='equity_liability'||mapping.side==='income'?-1:1;row.current+=sign*(current.get(mapping.groupId)??0);row.prior+=sign*(prior.get(mapping.groupId)??0);row.groupIds.push(mapping.groupId);const ids=db.prepare(`SELECT DISTINCT v.id FROM vouchers v JOIN voucher_lines vl ON vl.voucher_id=v.id JOIN ledgers l ON l.id=vl.ledger_id WHERE l.group_id=? AND v.date<=? AND ${IN_BOOKS}`).all(mapping.groupId,asOn) as {id:number}[];row.voucherIds.push(...ids.map((item)=>item.id))}const mapped=new Set(mappings.map((row)=>row.groupId));const unmapped=groups.filter((group)=>!mapped.has(group.id)&&(current.get(group.id)??0)!==0).map((group)=>({groupId:group.id,groupName:group.name,nature:group.nature,amount:current.get(group.id)??0}));return{asOn,priorAsOn,rows:rows.map((row)=>({...row,voucherIds:[...new Set(row.voucherIds)]})),unmapped}}
