import { describe,expect,it } from 'vitest'
import { seededDb } from '../db/testdb'
import { savePriceLevel,saveRate } from './priceLevels'
import { generateSalesRecurringBatch,listSalesRecurringSchedules,previewSalesRecurringBatch,saveSalesRecurringSchedule } from './salesRecurring'
import { assertDiscountAuthority,discountAuthority,invoiceDiscountBps,saveDiscountPolicy } from './discountAuthority'
import { createSalesDocument,listSalesDocumentSeries } from './salesDocuments'

function fixtures(){const db=seededDb();const group=(name:string)=>(db.prepare('SELECT id FROM groups WHERE name=?').get(name) as {id:number}).id;const unit=(db.prepare('SELECT id FROM units LIMIT 1').get() as {id:number}).id;const itemId=Number(db.prepare("INSERT INTO stock_items(name,unit_id,gst_rate) VALUES('Service Kit',?,18)").run(unit).lastInsertRowid);const customerId=Number(db.prepare("INSERT INTO ledgers(name,group_id) VALUES('Orbit Stores',?)").run(group('Sundry Debtors')).lastInsertRowid);const salesTypeId=(db.prepare("SELECT id FROM voucher_types WHERE kind='sales' LIMIT 1").get() as {id:number}).id;return{db,itemId,customerId,salesTypeId}}

describe('recurring sales billing',()=>{
  it('previews every due occurrence, resolves customer-effective prices, and generates editable drafts only',()=>{const{db,itemId,customerId,salesTypeId}=fixtures();const level=savePriceLevel(db,{name:'Contract pricing'});saveRate(db,{priceLevelId:level.id,stockItemId:itemId,rate:250_000,effectiveFrom:'2026-04-01'});db.prepare('UPDATE ledgers SET price_level_id=? WHERE id=?').run(level.id,customerId);const schedule=saveSalesRecurringSchedule(db,{name:'Orbit care plan',partyLedgerId:customerId,voucherTypeId:salesTypeId,cadence:'monthly',nextDue:'2026-08-31',endDate:null,dueDays:15,lines:[{stockItemId:itemId,description:'Monthly care plan',qtyMilli:1000,rateMode:'price_list',fixedRate:null,discountBps:1000}],narration:'Monthly support subscription',active:true},'Meera');const preview=previewSalesRecurringBatch(db,'2026-10-31');expect(preview).toMatchObject({readyCount:3,exceptionCount:0,totalAmount:796_500,rows:[{dueDate:'2026-08-31',amount:265_500},{dueDate:'2026-09-30'},{dueDate:'2026-10-30'}]});const batch=generateSalesRecurringBatch(db,'2026-10-31',[schedule.id],'Meera');expect(batch.rows).toHaveLength(3);expect(batch.rows.every((row)=>row.status==='generated'&&row.voucherDraftId)).toBe(true);expect((db.prepare('SELECT COUNT(*) AS n FROM vouchers').get() as {n:number}).n).toBe(0);expect((db.prepare('SELECT COUNT(*) AS n FROM voucher_drafts').get() as {n:number}).n).toBe(3);expect(listSalesRecurringSchedules(db)[0]).toMatchObject({nextDue:'2026-11-30',lastGenerated:'2026-10-30'})})
  it('surfaces missing customer prices as retained exceptions without advancing the schedule',()=>{const{db,itemId,customerId,salesTypeId}=fixtures();const schedule=saveSalesRecurringSchedule(db,{name:'Unpriced renewal',partyLedgerId:customerId,voucherTypeId:salesTypeId,cadence:'yearly',nextDue:'2026-08-24',endDate:null,dueDays:0,lines:[{stockItemId:itemId,description:'Renewal',qtyMilli:1000,rateMode:'price_list',fixedRate:null,discountBps:0}],narration:null,active:true},'Meera');expect(previewSalesRecurringBatch(db,'2026-08-24')).toMatchObject({readyCount:0,exceptionCount:1,rows:[{status:'exception',message:'Line 1: no effective customer price on 2026-08-24'}]});const batch=generateSalesRecurringBatch(db,'2026-08-24',[schedule.id],'Meera');expect(batch.rows).toMatchObject([{status:'exception',voucherDraftId:null}]);expect(listSalesRecurringSchedules(db)[0]?.nextDue).toBe('2026-08-24')})
})

describe('discount authority',()=>{
  it('uses the most restrictive applicable role, item, customer or global limit',()=>{const{db,itemId,customerId}=fixtures();saveDiscountPolicy(db,{name:'Company ceiling',scopeKind:'global',role:null,stockItemId:null,customerLedgerId:null,maxDiscountBps:2000,active:true},'Owner');saveDiscountPolicy(db,{name:'Accountant authority',scopeKind:'role',role:'accountant',stockItemId:null,customerLedgerId:null,maxDiscountBps:1000,active:true},'Owner');saveDiscountPolicy(db,{name:'Protected item',scopeKind:'item',role:null,stockItemId:itemId,customerLedgerId:null,maxDiscountBps:500,active:true},'Owner');saveDiscountPolicy(db,{name:'Orbit contract',scopeKind:'customer',role:null,stockItemId:null,customerLedgerId:customerId,maxDiscountBps:750,active:true},'Owner');expect(discountAuthority(db,'accountant',customerId,itemId,500)).toMatchObject({allowed:true,maxDiscountBps:500,policyNames:['Protected item']});expect(discountAuthority(db,'accountant',customerId,itemId,501)).toMatchObject({allowed:false,maxDiscountBps:500});expect(discountAuthority(db,'owner',customerId,null,1000)).toMatchObject({allowed:false,maxDiscountBps:750})})
  it('blocks excessive discounts in operational documents and records the denied attempt',()=>{const{db,itemId,customerId}=fixtures();saveDiscountPolicy(db,{name:'Sales team maximum',scopeKind:'role',role:'accountant',stockItemId:null,customerLedgerId:null,maxDiscountBps:1000,active:true},'Owner');const series=listSalesDocumentSeries(db,'quotation')[0]!;expect(()=>createSalesDocument(db,{kind:'quotation',seriesId:series.id,partyLedgerId:customerId,date:'2026-08-24',validUntil:null,purpose:null,gstRegistrationId:null,terms:[],customFields:{},lines:[{stockItemId:itemId,description:'Service Kit',qtyMilli:1000,rate:10_000,discountBps:1500,gstRate:18}]},'Asha',null,'accountant')).toThrow('exceeds the 10% authority limit');expect(db.prepare("SELECT requested_discount_bps AS requested,allowed_discount_bps AS allowed,outcome FROM sales_discount_events").get()).toEqual({requested:1500,allowed:1000,outcome:'blocked'});expect((db.prepare('SELECT COUNT(*) AS n FROM sales_documents').get() as {n:number}).n).toBe(0)})
  it('calculates invoice discount percentage conservatively from integer paise',()=>{expect(invoiceDiscountBps(3000,10_000,3_000)).toBe(1000);expect(invoiceDiscountBps(3000,10_000,3_001)).toBe(1001);const{db,itemId,customerId}=fixtures();saveDiscountPolicy(db,{name:'Ten percent',scopeKind:'global',role:null,stockItemId:null,customerLedgerId:null,maxDiscountBps:1000,active:true},'Owner');expect(()=>assertDiscountAuthority(db,{role:'owner',actorName:'Owner',customerLedgerId:customerId,contextKind:'sales_invoice',lines:[{stockItemId:itemId,requestedDiscountBps:1001}]})).toThrow('10.01%')})
})
