import type { DB } from '../db/connection'
import type { VendorOnboardingIssue, VendorProfile, VendorProfileInput } from '@shared/procurement'
import { writeAudit } from './audit'

interface VendorRow {
  id:number;ledgerId:number;supplierName:string;gstin:string|null;pan:string|null;contactName:string|null;email:string|null;phone:string|null;bankName:string|null;bankAccount:string|null;ifsc:string|null;udyamNumber:string|null;status:VendorProfile['status'];reviewNote:string|null;verifiedBy:string|null;verifiedAt:string|null;updatedAt:string
}

const SELECT=`SELECT vp.id,vp.ledger_id AS ledgerId,l.name AS supplierName,l.gstin,l.pan,vp.contact_name AS contactName,vp.email,vp.phone,vp.bank_name AS bankName,vp.bank_account AS bankAccount,vp.ifsc,vp.udyam_number AS udyamNumber,vp.status,vp.review_note AS reviewNote,vp.verified_by AS verifiedBy,vp.verified_at AS verifiedAt,vp.updated_at AS updatedAt FROM vendor_profiles vp JOIN ledgers l ON l.id=vp.ledger_id`

function normalize(input:VendorProfileInput):VendorProfileInput{return{ledgerId:input.ledgerId,contactName:input.contactName?.trim()||null,email:input.email?.trim().toLowerCase()||null,phone:input.phone?.replace(/[^0-9+]/g,'')||null,bankName:input.bankName?.trim()||null,bankAccount:input.bankAccount?.replace(/\s+/g,'').toUpperCase()||null,ifsc:input.ifsc?.trim().toUpperCase()||null,udyamNumber:input.udyamNumber?.trim().toUpperCase()||null}}

export function vendorIssues(db:DB,input:VendorProfileInput,excludeLedgerId?:number):VendorOnboardingIssue[]{
  const value=normalize(input);const issues:VendorOnboardingIssue[]=[];const ledger=db.prepare('SELECT gstin,pan FROM ledgers WHERE id=?').get(value.ledgerId) as {gstin:string|null;pan:string|null}|undefined;if(!ledger)return[{field:'pan',severity:'block',message:'Supplier ledger was not found'}]
  const duplicateLedger=(field:'gstin'|'pan',candidate:string|null):void=>{if(!candidate)return;const row=db.prepare(`SELECT name FROM ledgers WHERE ${field}=? AND id<>? LIMIT 1`).get(candidate,excludeLedgerId??value.ledgerId) as {name:string}|undefined;if(row)issues.push({field,severity:'block',message:`${field.toUpperCase()} is already used by ${row.name}`})};duplicateLedger('gstin',ledger.gstin);duplicateLedger('pan',ledger.pan)
  const duplicateProfile=(field:'email'|'phone'|'bank_account',candidate:string|null,severity:'block'|'review'):void=>{if(!candidate)return;const col=field==='bank_account'?'bank_account':field;const row=db.prepare(`SELECT l.name FROM vendor_profiles vp JOIN ledgers l ON l.id=vp.ledger_id WHERE vp.${col}=? COLLATE NOCASE AND vp.ledger_id<>? LIMIT 1`).get(candidate,excludeLedgerId??value.ledgerId) as {name:string}|undefined;if(row)issues.push({field,severity,message:`${field.replace('_',' ')} also appears on ${row.name}`})};duplicateProfile('email',value.email,'review');duplicateProfile('phone',value.phone,'review');duplicateProfile('bank_account',value.bankAccount,'block')
  return issues
}

function map(db:DB,row:VendorRow,maskBank:boolean):VendorProfile{const issues=vendorIssues(db,{ledgerId:row.ledgerId,contactName:row.contactName,email:row.email,phone:row.phone,bankName:row.bankName,bankAccount:row.bankAccount,ifsc:row.ifsc,udyamNumber:row.udyamNumber},row.ledgerId);return{...row,bankAccount:maskBank&&row.bankAccount?`••••${row.bankAccount.slice(-4)}`:row.bankAccount,issues}}
export function listVendorProfiles(db:DB,maskBank=false):VendorProfile[]{return(db.prepare(`${SELECT} ORDER BY vp.updated_at DESC,vp.id DESC`).all() as VendorRow[]).map((row)=>map(db,row,maskBank))}
export function getVendorProfile(db:DB,ledgerId:number,maskBank=false):VendorProfile|null{const row=db.prepare(`${SELECT} WHERE vp.ledger_id=?`).get(ledgerId) as VendorRow|undefined;return row?map(db,row,maskBank):null}

export function saveVendorProfile(db:DB,input:VendorProfileInput,author:string):VendorProfile{
  const value=normalize(input);const supplier=db.prepare(`WITH RECURSIVE creditor_groups(id) AS (SELECT id FROM groups WHERE name='Sundry Creditors' UNION ALL SELECT g.id FROM groups g JOIN creditor_groups p ON g.parent_id=p.id) SELECT l.id FROM ledgers l WHERE l.id=? AND l.group_id IN(SELECT id FROM creditor_groups)`).get(value.ledgerId);if(!supplier)throw new Error('Choose a supplier ledger under Sundry Creditors')
  if(value.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value.email))throw new Error('Enter a valid supplier email');if(value.phone&&value.phone.replace(/\D/g,'').length<10)throw new Error('Enter a valid supplier phone');if(value.bankAccount&&!/^[A-Z0-9]{6,34}$/.test(value.bankAccount))throw new Error('Bank account must contain 6–34 letters or digits');if((value.bankAccount&&!value.ifsc)||(!value.bankAccount&&value.ifsc))throw new Error('Bank account and IFSC must be entered together');if(value.ifsc&&!/^[A-Z]{4}0[A-Z0-9]{6}$/.test(value.ifsc))throw new Error('Enter a valid IFSC');if(value.udyamNumber&&!/^UDYAM-[A-Z]{2}-\d{2}-\d{7}$/.test(value.udyamNumber))throw new Error('Enter UDYAM as UDYAM-XX-00-0000000')
  const before=getVendorProfile(db,value.ledgerId);db.prepare(`INSERT INTO vendor_profiles(ledger_id,contact_name,email,phone,bank_name,bank_account,ifsc,udyam_number) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(ledger_id) DO UPDATE SET contact_name=excluded.contact_name,email=excluded.email,phone=excluded.phone,bank_name=excluded.bank_name,bank_account=excluded.bank_account,ifsc=excluded.ifsc,udyam_number=excluded.udyam_number,status='draft',review_note=NULL,verified_by=NULL,verified_at=NULL,updated_at=datetime('now')`).run(value.ledgerId,value.contactName,value.email,value.phone,value.bankName,value.bankAccount,value.ifsc,value.udyamNumber);const after=getVendorProfile(db,value.ledgerId)!;writeAudit(db,'vendor_profile',after.id,before?'update':'create',before?{status:before.status}:null,{status:'draft',by:author});return after
}

export function setVendorStatus(db:DB,ledgerId:number,status:'verified'|'blocked'|'draft',author:string,note?:string|null):VendorProfile{
  const before=getVendorProfile(db,ledgerId);if(!before)throw new Error('Vendor profile was not found');if(status==='verified'){const blockers=before.issues.filter((issue)=>issue.severity==='block');if(blockers.length)throw new Error(blockers.map((issue)=>issue.message).join('; '));if(!before.contactName||(!before.email&&!before.phone))throw new Error('Add a contact name and email or phone before verification')}if(status==='blocked'&&(note?.trim().length??0)<3)throw new Error('Enter a reason for blocking this vendor')
  db.prepare(`UPDATE vendor_profiles SET status=?,review_note=?,verified_by=?,verified_at=?,updated_at=datetime('now') WHERE ledger_id=?`).run(status,note?.trim()||null,status==='verified'?author:null,status==='verified'?new Date().toISOString():null,ledgerId);const after=getVendorProfile(db,ledgerId)!;writeAudit(db,'vendor_profile',after.id,'update',{status:before.status},{status,by:author,note});return after
}
