import { describe, expect, it } from 'vitest'
import { CODE128_PATTERNS, code128Modules, code128Svg, code128Values } from './code128'

// Known vectors: the full module bit string (check + stop included, quiet zones excluded) as
// generated by python-barcode 0.15 (barcode.codex.Code128().build()), an independent
// implementation, and the start + data symbols decoded from those bits. Not a dependency: the
// vectors are pasted here.
const VECTORS: [string, number[], string][] = [
  ['PJJ123C', [104, 48, 42, 42, 17, 18, 19, 35], '1101001000011101110110101101110001011011100010011100110110011100101100101110010001000110111010001101100011101011'],
  ['Wikipedia', [104, 55, 73, 75, 73, 80, 69, 68, 73, 65], '11010010000111010001101000011010011000010010100001101001010011110010110010000100001001101000011010010010110000111100100101100011101011'],
  ['12345', [105, 12, 34, 100, 21], '1101001110010110011100100010110001011110111011011100100111010110001100011101011'],
  ['123', [104, 17, 18, 19], '11010010000100111001101100111001011001011100100011001001100011101011'],
  ['12', [105, 12], '1101001110010110011100100110011101100011101011'],
  ['ITEM0042', [104, 41, 52, 37, 45, 99, 0, 42], '1101001000011000100010110111000101000110100010111011000101110111101101100110010110111000101000111101100011101011'],
  ['A1234567B', [104, 33, 99, 12, 34, 56, 100, 23, 34], '110100100001010001100010111011110101100111001000101100011100010110101111011101110110111010001011000101100100001100011101011'],
  ['SKU-889900112', [104, 51, 43, 53, 13, 99, 88, 99, 0, 11, 100, 18], '110100100001101110100010110001110110111011101001101110010111011110111100100101011101111011011001100110001001001011110111011001110010100100001101100011101011'],
  ['8901234567890', [105, 89, 1, 23, 45, 67, 89, 100, 16], '110100111001101101111011001101100111011011101011101100010000101100110110111101011110111010011101100100100111101100011101011'],
  ['HELLO world!', [104, 40, 37, 44, 44, 47, 0, 87, 79, 82, 76, 68, 1], '11010010000110001010001000110100010001101110100011011101000111011011011001100111100101001000111101010010011110110010100001000010011011001101100100011010001100011101011'],
  ['AB12C', [104, 33, 34, 17, 18, 35], '110100100001010001100010001011000100111001101100111001010001000110111101101101100011101011'],
  ['1AB', [104, 17, 33, 34], '11010010000100111001101010001100010001011000101111001001100011101011']
]

const bits = (modules: number[]): string => modules.map((w, i) => (i % 2 === 0 ? '1' : '0').repeat(w)).join('')

describe('code128', () => {
  it('pattern table: 107 symbols, 3 bars + 3 spaces over 11 modules (stop: 13), all distinct', () => {
    expect(CODE128_PATTERNS).toHaveLength(107)
    CODE128_PATTERNS.forEach((p, v) => {
      const widths = [...p].map(Number)
      expect(widths.reduce((s, w) => s + w, 0)).toBe(v === 106 ? 13 : 11)
      expect(widths.every((w) => w >= 1 && w <= 4)).toBe(true)
    })
    expect(new Set(CODE128_PATTERNS).size).toBe(107)
  })

  it.each(VECTORS)('encodes %s like the reference encoder', (text, data, expectedBits) => {
    const values = code128Values(text)
    expect(values.slice(0, -2)).toEqual(data)
    let sum = data[0]!
    data.slice(1).forEach((v, k) => (sum += v * (k + 1)))
    expect(values[values.length - 2]).toBe(sum % 103)
    expect(values[values.length - 1]).toBe(106)
    expect(bits(code128Modules(text))).toBe(expectedBits)
  })

  it('PJJ123C check symbol by hand: (104 + 48·1 + 42·2 + 42·3 + 17·4 + 18·5 + 19·6 + 35·7) mod 103 = 55', () => {
    expect(code128Values('PJJ123C').at(-2)).toBe(55)
  })

  it('rejects empty text and characters outside ASCII 32–127', () => {
    expect(() => code128Values('')).toThrow(/Nothing/)
    expect(() => code128Values('café')).toThrow(/can't encode/)
    expect(() => code128Values('a\tb')).toThrow(/can't encode/)
  })

  it('svg: one rect per bar, width = (modules + quiet zones) × module width', () => {
    const svg = code128Svg('ITEM0042', { moduleWidth: 1, height: 40 })
    const modules = code128Modules('ITEM0042')
    const total = modules.reduce((s, m) => s + m, 0) + 20
    expect(svg).toContain(`width="${total}"`)
    expect(svg.match(/<rect x=/g)).toHaveLength(Math.ceil(modules.length / 2))
  })
})
